# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_submission_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission_location',
            new_name='submissionLocation',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='submission_time',
            new_name='submissionTime',
        ),
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.IntegerField(default=-1),
        ),
    ]
