# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_auto_20170524_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submissionTime',
            field=models.IntegerField(verbose_name='Time Added'),
        ),
    ]
